services:
  deepstream-dev:
    build:
      dockerfile: Dockerfile
      context: .
    tty: true
    stdin_open: true
    runtime: nvidia
    network: host
    volumes:
      - ./src:/app/src
      - ~/data:/app/data
      - ./setup.sh:/app/setup.sh
      - ./Dockerfile:/app/Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
